language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
sudo: required
install:
  - python3 setup.py bdist_wheel
  - version=$(python3 setup.py --version)
  - cd debian
  - . ./build_deb.sh pyhp-test ../dist/pyhp_core-$version-py3-none-any.whl pip
  - sudo dpkg -i pyhp-test.deb
  - cd ../examples
script:
  - . ./embedding.sh
  - . ./caching.sh
  - . ./request.sh
  - . ./header.sh
  - . ./cookie.sh
  - . ./shutdown_functions.sh
