#!/usr/bin/python3

# script to support the pyhp command

import sys
from pyhp.main import main, get_args

# get cli arguments
args = get_args()
file = args.pop("file_path")
# execute main with file_path as normal argument and the rest as keyword arguments
sys.exit(main(file, **args))
