name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  Test:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10.0-alpha.4", "pypy-3.7"]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
  
    steps:
    # setup
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # dependencies
    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}

    - name: Install test dependencies
      run: python -m pip --cache-dir ~/.cache/pip install --quiet wheel setuptools coverage

    # test
    - name: Build wheel
      run: python setup.py bdist_wheel

    - name: Install wheel
      run: python -m pip install "dist/pyhp_core-$(python setup.py --version)-py3-none-any.whl[CONFIG,PHP]"
      shell: bash

    - name: run tests
      run: coverage run -m unittest discover --verbose

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        flags: ${{ runner.os }}
  
  Typecheck:
    runs-on: ubuntu-latest
    steps:
    # setup
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    # dependencies
    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}

    - name: Install test dependencies
      run: python -m pip --cache-dir ~/.cache/pip install --quiet mypy types-toml types-werkzeug

    # check
    - name: run MyPy
      run: python -m mypy --config-file setup.cfg -p pyhp
